name: Build

on: [ push ]

jobs:

  setup:
    uses: ./.github/workflows/base.yml
    with:
      os: ubuntu-latest

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - setup

    steps:
      - name: Run Build
        run: ./gradlew build

      - name: Upload App Build
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: build/libs/dig-all.jar

  cleanup:
    needs:
      - build
    uses: ./.github/workflows/cleanup.yml
    with:
      os: ubuntu-latest
