# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Test

on: [ push ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      test:
        name: Unit Tests
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v2

          - name: Run tests
            run: ./gradlew test
